name: workflow 1
on: push


jobs:
    mark:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Welcome 
              run: |
                echo "Hello world"
                sudo apt update -y
                sudo apt install cowsay -y
                cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
                cat dragon.txt